[project]
name = "gaming-pc-wakeup"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Gordon Choi", email = "thefirate@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.141.1",
    "uvicorn>=0.52.4",
]

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "pytest>=9.1.1",
    "ruff>=0.16.5",
]
